import Head from 'next/head'
import Navbar from "./navbar"
import styles from '@/styles/Layout.module.css'

import { ProSidebarProvider } from 'react-pro-sidebar';

export default function Layout({ children }) {
  return (
    <>
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    <ProSidebarProvider>
    <div style={{display: "flex", position:'absolute', width:'100vw'}}>
      <Navbar />
      <main className={styles.main}>{children}</main>   
    </div>

    </ProSidebarProvider>
    </>
  )
}